apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pacman
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: pacman
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/wizardsisr/pacman
      ref:
        branch: master
